#!/usr/bin/env python3
"""Prepare Five Nines' sprites from their generated originals.

    python3 tools/prepare-dc-sprites.py [--source ~/aronwagner-art/generated]

Needs Python 3 with Pillow. Reads three transparent ChatGPT sheets (prompts are in
assets/five-nines/prompts/) and writes assets/five-nines/sprites/*.webp plus
assets/five-nines/sprite-data.js, which records where everything sits:

  aron.webp    10 poses, one shared scale, each centered on his feet;
  racks.webp   5 tall pieces side by side at one shared scale, feet on the bottom;
  props.webp   20 props, customers and effects in an atlas.
"""

import argparse
import json
import sys
from pathlib import Path

from PIL import Image

sys.path.insert(0, str(Path(__file__).resolve().parent / 'lib'))
from sprite_sheets import atlas, cut_grid, normalized, pose_strip  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
GAME = ROOT / 'assets' / 'five-nines'

ARON_POSES = [
    'stand', 'walkA', 'walkB', 'run', 'plug',
    'drive', 'spray', 'type', 'celebrate', 'stressed',
]
ARON_CELL = (540, 500)
RACKS = ['rack', 'rack-open', 'network', 'cooling', 'door']
RACK_HEIGHT = 720
PROPS = [
    'help-desk', 'drive-cart', 'tv', 'extinguisher', 'red-button',
    'cable', 'drive', 'pizza', 'coffee-cart', 'boxes',
    'dev', 'polo', 'glasses', 'founder', 'grandma',
    'flame-s', 'flame-m', 'flame-l', 'foam', 'smoke',
]
PROP_CELL = 360


def load(source, name):
    return normalized(Image.open(source / name).convert('RGBA'))


def main():
    parser = argparse.ArgumentParser(description=__doc__.split('\n')[0])
    parser.add_argument('--source', type=Path, default=Path.home() / 'aronwagner-art' / 'generated')
    source = parser.parse_args().source.expanduser()
    out = GAME / 'sprites'
    out.mkdir(parents=True, exist_ok=True)
    data = {}

    # One scale for every pose so Aron doesn't grow or shrink as he switches.
    aron = cut_grid(load(source, '11-dc-aron.png'), 5, 2)
    scale = min(1, (ARON_CELL[1] - 12) / max(figure.height for figure in aron))
    pose_strip(aron, ARON_CELL, scale).save(out / 'aron.webp', 'WEBP', quality=90, method=6)
    data['aron'] = {'cell': ARON_CELL, 'poses': ARON_POSES}

    # The racks were drawn at one height; keep their relative sizes.
    racks = cut_grid(load(source, '12-dc-racks.png'), 5, 1)
    scale = RACK_HEIGHT / max(figure.height for figure in racks)
    scaled = [
        figure.resize((round(figure.width * scale), round(figure.height * scale)), Image.LANCZOS)
        for figure in racks
    ]
    strip = Image.new('RGBA', (sum(figure.width + 8 for figure in scaled), RACK_HEIGHT + 8))
    x, rects = 4, {}
    for name, figure in zip(RACKS, scaled):
        y = strip.height - 4 - figure.height
        strip.alpha_composite(figure, (x, y))
        rects[name] = [x, y, figure.width, figure.height]
        x += figure.width + 8
    strip.save(out / 'racks.webp', 'WEBP', quality=88, method=6)
    data['racks'] = rects

    props = cut_grid(load(source, '13-dc-props.png'), 5, 4)
    image, rects = atlas(props, PROP_CELL, 5)
    image.save(out / 'props.webp', 'WEBP', quality=90, method=6)
    data['props'] = {name: rect for name, rect in zip(PROPS, rects)}

    module = GAME / 'sprite-data.js'
    module.write_text(
        '// Generated by tools/prepare-dc-sprites.py. Do not edit.\n'
        f'export const SPRITES = {json.dumps(data, indent=2)};\n'
    )
    for name in ('aron', 'racks', 'props'):
        path = out / f'{name}.webp'
        print(f'{path.relative_to(ROOT)}: {path.stat().st_size // 1024} KiB')
    print(f'{module.relative_to(ROOT)}: written')


if __name__ == '__main__':
    main()
