#!/usr/bin/env python3
"""Prepare Tee Time's sprites from their generated originals.

    python3 tools/prepare-golf-sprites.py [--source ~/aronwagner-art/generated]

Needs Python 3 with Pillow. Reads three transparent ChatGPT sheets (prompts are in
assets/tee-time/prompts/) and writes assets/tee-time/sprites/*.webp plus
assets/tee-time/sprite-data.js, which records where everything sits:

  aron.webp    6 golf poses, one shared scale, each centered on his feet;
  maggie.webp  6 poses of Maggie with and without the ball, centered on her feet;
  props.webp   20 props in an atlas; sprite-data.js has each one's rectangle.
"""

import argparse
import json
import sys
from pathlib import Path

from PIL import Image

sys.path.insert(0, str(Path(__file__).resolve().parent / 'lib'))
from sprite_sheets import atlas, cut_grid, normalized, pose_strip  # noqa: E402

ROOT = Path(__file__).resolve().parent.parent
GAME = ROOT / 'assets' / 'tee-time'

ARON_POSES = ['address', 'backswing', 'follow', 'putt', 'celebrate', 'frustrated']
ARON_CELL = (420, 540)
MAGGIE_POSES = ['runBallA', 'runBallB', 'runA', 'runB', 'sit', 'bow']
MAGGIE_CELL = (330, 276)
MAGGIE_SCALE = 0.6
PROPS = [
    'desk', 'chair', 'sofa', 'coffee-table', 'island',
    'blocks', 'dog-bed', 'toy-basket', 'fridge', 'patio-door',
    'palm', 'oak', 'flag', 'cart', 'bench',
    'gator', 'tee-markers', 'grill', 'potted-palm', 'rebecca-jack',
]
PROP_CELL = 300


def load(source, name):
    return normalized(Image.open(source / name).convert('RGBA'))


def main():
    parser = argparse.ArgumentParser(description=__doc__.split('\n')[0])
    parser.add_argument('--source', type=Path, default=Path.home() / 'aronwagner-art' / 'generated')
    source = parser.parse_args().source.expanduser()
    out = GAME / 'sprites'
    out.mkdir(parents=True, exist_ok=True)
    data = {}

    # All six swing poses were drawn at one scale, so keep it: the club and the
    # stance line up when the game switches poses over the ball.
    aron = cut_grid(load(source, '08-golf-aron-swing.png'), 3, 2)
    scale = (ARON_CELL[1] - 12) / max(figure.height for figure in aron)
    strip = pose_strip(aron, ARON_CELL, scale)
    strip.save(out / 'aron.webp', 'WEBP', quality=90, method=6)
    # Where the clubhead rests at address and at the putt: the rightmost visible
    # pixel in the bottom band of the pose, relative to the feet anchor.
    clubhead = {}
    for pose in ('address', 'putt'):
        index = ARON_POSES.index(pose)
        cell = strip.crop((index * ARON_CELL[0], 0, (index + 1) * ARON_CELL[0], ARON_CELL[1]))
        band = cell.getchannel('A').point(lambda v: 255 if v > 128 else 0)
        box = band.crop((0, ARON_CELL[1] - 40, ARON_CELL[0], ARON_CELL[1])).getbbox()
        clubhead[pose] = [box[2] - 14 - ARON_CELL[0] / 2, box[3] - 40]
    data['aron'] = {
        'cell': ARON_CELL,
        'poses': ARON_POSES,
        'scale': round(scale, 4),
        'clubhead': clubhead,
    }

    maggie = cut_grid(load(source, '09-golf-maggie.png'), 3, 2)
    pose_strip(maggie, MAGGIE_CELL, MAGGIE_SCALE).save(out / 'maggie.webp', 'WEBP', quality=90, method=6)
    data['maggie'] = {'cell': MAGGIE_CELL, 'poses': MAGGIE_POSES}

    props = cut_grid(load(source, '10-golf-props.png'), 5, 4)
    image, rects = atlas(props, PROP_CELL, 5)
    image.save(out / 'props.webp', 'WEBP', quality=90, method=6)
    data['props'] = {name: rect for name, rect in zip(PROPS, rects)}

    module = GAME / 'sprite-data.js'
    module.write_text(
        '// Generated by tools/prepare-golf-sprites.py. Do not edit.\n'
        f'export const SPRITES = {json.dumps(data, indent=2)};\n'
    )
    for name in ('aron', 'maggie', 'props'):
        path = out / f'{name}.webp'
        print(f'{path.relative_to(ROOT)}: {path.stat().st_size // 1024} KiB')
    print(f'{module.relative_to(ROOT)}: written')


if __name__ == '__main__':
    main()
